"""
All constants used throughout gridmind.
No magic numbers anywhere else in the codebase — they must live here.
"""

# Package metadata
VERSION = "0.1.0"
PACKAGE_NAME = "gridmind"

# Solver configuration
DEFAULT_SOLVER = "CLARABEL"
FALLBACK_SOLVER = "ECOS"
SOLVER_TOLERANCE = 1e-4

# Optimisation intervals
DEFAULT_INTERVAL_MINUTES = 15
MIN_INTERVAL_MINUTES = 1
MAX_INTERVAL_MINUTES = 60

# Time unit conversions
SECONDS_PER_MINUTE = 60
MINUTES_PER_HOUR = 60
HOURS_PER_DAY = 24

# Power unit conversions
WATTS_PER_KW = 1000.0

# Power thresholds
MIN_POWER_THRESHOLD_W = 1.0
MAX_SINGLE_EV_POWER_W = 22080.0

# SoC constraints
SOC_TOLERANCE_PERCENT = 0.5
MIN_SOC_DEFAULT_PERCENT = 10.0
MAX_SOC_PERCENT = 100.0

# OCPP 1.6 limits
OCPP16_MAX_PERIODS_PER_PROFILE = 1024
OCPP16_MAX_STACK_LEVEL = 9  # 0-based; valid range 0-9
OCPP16_MIN_CONNECTOR_ID = 0
OCPP16_MIN_CHARGING_RATE_W = 1400.0  # 6A x 230V, IEC 61851 AC minimum

# AC charging
DEFAULT_VOLTAGE_V = 230.0
THREE_PHASE_VOLTAGE_V = 400.0
DEFAULT_FREQUENCY_HZ = 50.0
DEFAULT_CHARGING_EFFICIENCY = 0.92

# Common charger power ratings (W)
CHARGER_3_7KW_W = 3680.0  # 16A x 230V, EU slow charger
CHARGER_7_4KW_W = 7360.0
CHARGER_11KW_W = 11000.0
CHARGER_22KW_W = 22080.0

# Common EV battery capacities (kWh)
BATTERY_SMALL_KWH = 30.0
BATTERY_MEDIUM_KWH = 60.0
BATTERY_LARGE_KWH = 90.0

# Default electricity pricing
DEFAULT_FLAT_RATE_EUR_KWH = 0.25
DEFAULT_CHEAP_RATE_EUR_KWH = 0.10
DEFAULT_PEAK_RATE_EUR_KWH = 0.35

# Visualisation
PLOT_DPI = 150
PLOT_FIGSIZE_SINGLE = (12, 6)
PLOT_FIGSIZE_FLEET = (14, 8)
PLOT_FIGSIZE_COMPARISON = (16, 10)
COLOUR_OPTIMISED = "#1D9E75"
COLOUR_UNCONTROLLED = "#E24B4A"
COLOUR_GRID_LIMIT = "#BA7517"
COLOUR_PRICE = "#378ADD"
